eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  security:
    user:
      name: admin
      password: eureka

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:eureka@localhost:8762/eureka/,http://admin:eureka@localhost:8763/eureka/
server:
  port: 8761

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:eureka@localhost:8761/eureka/,http://admin:eureka@localhost:8763/eureka/
server:
  port: 8762

---
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:eureka@localhost:8761/eureka/,http://admin:eureka@localhost:8762/eureka/
server:
  port: 8763

---
spring:
  profiles: es1
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:eureka@eureka-server-2:8761/eureka/,http://admin:eureka@eureka-server-3:8761/eureka/

---
spring:
  profiles: es2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:eureka@eureka-server-1:8761/eureka/,http://admin:eureka@eureka-server-3:8761/eureka/

---
spring:
  profiles: es3
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:eureka@eureka-server-1:8761/eureka/,http://admin:eureka@eureka-server-2:8761/eureka/
